- name: Update packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Install wireguard
  apt:
    name: wireguard=1.0.20200319-1ubuntu1

- name: Change to Wireguard directory and then generate keys
  shell:  umask 077; wg genkey | tee privatekey | wg pubkey > publickey
  args:
    chdir: /etc/wireguard/
    creates: /etc/wireguard/privatekey

- name: Slurp hosts file
  slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_private_key_file

- name: Slurp hosts file
  slurp:
    src: /etc/wireguard/publickey
  register: wireguard_public_key_file

- set_fact:
     wireguard_private_key: "{{ wireguard_private_key_file['content'] | b64decode }}"

- set_fact:
     wireguard_public_key: "{{ wireguard_public_key_file['content'] | b64decode }}"

- name: Stop wireguard before editing file.
  systemd:
    state: stopped
    name: wg-quick@wg0
